# coding: utf-8

"""
    GroundX APIs

    RAG Made Simple, Secure and Hallucination Free

    The version of the OpenAPI document: 1.3.26
    Contact: support@eyelevel.ai
    Created by: https://www.eyelevel.ai/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from groundx import schemas  # noqa: F401


class DocumentLocalIngestRequest(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['DocumentLocalIngestRequestItem']:
            return DocumentLocalIngestRequestItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['DocumentLocalIngestRequestItem'], typing.List['DocumentLocalIngestRequestItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'DocumentLocalIngestRequest':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'DocumentLocalIngestRequestItem':
        return super().__getitem__(i)

from groundx.model.document_local_ingest_request_item import DocumentLocalIngestRequestItem
