# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from groundx import schemas  # noqa: F401


class PreprocessorResponsePreprocess(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def preprocessors() -> typing.Type['PreprocessorResponsePreprocessPreprocessors']:
                return PreprocessorResponsePreprocessPreprocessors
            __annotations__ = {
                "preprocessors": preprocessors,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["preprocessors"]) -> 'PreprocessorResponsePreprocessPreprocessors': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["preprocessors", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["preprocessors"]) -> typing.Union['PreprocessorResponsePreprocessPreprocessors', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["preprocessors", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        preprocessors: typing.Union['PreprocessorResponsePreprocessPreprocessors', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PreprocessorResponsePreprocess':
        return super().__new__(
            cls,
            *args,
            preprocessors=preprocessors,
            _configuration=_configuration,
            **kwargs,
        )

from groundx.model.preprocessor_response_preprocess_preprocessors import PreprocessorResponsePreprocessPreprocessors
