# coding: utf-8

"""
    GroundX APIs

    RAG Made Simple, Secure and Hallucination Free

    The version of the OpenAPI document: 1.3.26
    Contact: support@eyelevel.ai
    Created by: https://www.eyelevel.ai/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from groundx import schemas  # noqa: F401


class SubscriptionDetailMeters(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def fileTokens() -> typing.Type['MeterDetail']:
                return MeterDetail
        
            @staticmethod
            def searches() -> typing.Type['MeterDetail']:
                return MeterDetail
            __annotations__ = {
                "fileTokens": fileTokens,
                "searches": searches,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fileTokens"]) -> 'MeterDetail': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["searches"]) -> 'MeterDetail': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["fileTokens", "searches", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fileTokens"]) -> typing.Union['MeterDetail', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["searches"]) -> typing.Union['MeterDetail', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["fileTokens", "searches", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        fileTokens: typing.Union['MeterDetail', schemas.Unset] = schemas.unset,
        searches: typing.Union['MeterDetail', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SubscriptionDetailMeters':
        return super().__new__(
            cls,
            *args,
            fileTokens=fileTokens,
            searches=searches,
            _configuration=_configuration,
            **kwargs,
        )

from groundx.model.meter_detail import MeterDetail
