/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

import { AxiosRequestConfig } from "axios";
import {
  ApiKeyManagementApi,
  BucketApi,
  DocumentApi,
  PreprocessorApi,
  ProjectApi,
  SearchApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { GroundxCustom } from "./client-custom";

export class Groundx extends GroundxCustom {
  readonly apiKeyManagement: ApiKeyManagementApi;
  readonly bucket: BucketApi;
  readonly document: DocumentApi;
  readonly preprocessor: PreprocessorApi;
  readonly project: ProjectApi;
  readonly search: SearchApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.apiKeyManagement = new ApiKeyManagementApi(configuration);
    this.bucket = new BucketApi(configuration);
    this.document = new DocumentApi(configuration);
    this.preprocessor = new PreprocessorApi(configuration);
    this.project = new ProjectApi(configuration);
    this.search = new SearchApi(configuration);
  }

}
