# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from groundx import Groundx

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        groundx = Groundx(
            # Defining the host is optional and defaults to https://api.groundx.ai/api
            # See configuration.py for a list of all supported configuration parameters.
            host = "https://api.groundx.ai/api",
        
            # Configure API key authorization: ApiKeyAuth
            api_key = 'YOUR_API_KEY',
            # Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
            # api_key_prefix = {'ApiKeyAuth': 'Bearer'},
        )
        self.assertIsNotNone(groundx)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
