/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ApiKeyManagementList405Response
 */
export interface ApiKeyManagementList405Response {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyManagementList405Response
     */
    'message'?: string;
}

