/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface BucketDetail
 */
export interface BucketDetail {
    /**
     * 
     * @type {number}
     * @memberof BucketDetail
     */
    'bucketId'?: number;
    /**
     * 
     * @type {number}
     * @memberof BucketDetail
     */
    'fileCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof BucketDetail
     */
    'fileSize'?: string;
    /**
     * 
     * @type {string}
     * @memberof BucketDetail
     */
    'name'?: string;
}

