/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { BucketDetail } from './bucket-detail';

/**
 * 
 * @export
 * @interface BucketListResponse
 */
export interface BucketListResponse {
    /**
     * 
     * @type {Array<BucketDetail>}
     * @memberof BucketListResponse
     */
    'buckets'?: Array<BucketDetail>;
}

