/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BucketUpdateDetail
 */
export interface BucketUpdateDetail {
    /**
     * 
     * @type {number}
     * @memberof BucketUpdateDetail
     */
    'bucketId': number;
    /**
     * 
     * @type {string}
     * @memberof BucketUpdateDetail
     */
    'name'?: string;
}

