/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BucketUpdateRequest
 */
export interface BucketUpdateRequest {
    /**
     * The new name of the bucket being renamed.
     * @type {string}
     * @memberof BucketUpdateRequest
     */
    'newName': string;
}

