/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentRemoteIngestRequestDocumentsInner } from './document-remote-ingest-request-documents-inner';

/**
 * 
 * @export
 * @interface DocumentRemoteIngestRequest
 */
export interface DocumentRemoteIngestRequest {
    /**
     * 
     * @type {Array<DocumentRemoteIngestRequestDocumentsInner>}
     * @memberof DocumentRemoteIngestRequest
     */
    'documents': Array<DocumentRemoteIngestRequestDocumentsInner>;
}

