/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentDetail } from './document-detail';

/**
 * 
 * @export
 * @interface DocumentListResponse
 */
export interface DocumentListResponse {
    /**
     * 
     * @type {Array<DocumentDetail>}
     * @memberof DocumentListResponse
     */
    'documents'?: Array<DocumentDetail>;
    /**
     * 
     * @type {string}
     * @memberof DocumentListResponse
     */
    'nextToken'?: string;
}

