/*
EyeLevel\'s GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentDetail } from './document-detail';

/**
 * 
 * @export
 * @interface DocumentListResponse
 */
export interface DocumentListResponse {
    /**
     * 
     * @type {Array<DocumentDetail>}
     * @memberof DocumentListResponse
     */
    'documents'?: Array<DocumentDetail>;
    /**
     * 
     * @type {string}
     * @memberof DocumentListResponse
     */
    'nextToken'?: string;
}

