/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentResponseDocument
 */
export interface DocumentResponseDocument {
    /**
     * 
     * @type {number}
     * @memberof DocumentResponseDocument
     */
    'bucketId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'documentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'fileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'fileSize'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'fileType'?: string;
    /**
     * 
     * @type {object}
     * @memberof DocumentResponseDocument
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'processId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'processedUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'sourceUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentResponseDocument
     */
    'statusMessage'?: string;
}

