/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentResponse } from './document-response';

/**
 * 
 * @export
 * @interface DocumentLookupResponse
 */
export interface DocumentLookupResponse {
    /**
     * The number of results returned in the current response
     * @type {number}
     * @memberof DocumentLookupResponse
     */
    'count'?: number;
    /**
     * 
     * @type {Array<DocumentResponse>}
     * @memberof DocumentLookupResponse
     */
    'documents'?: Array<DocumentResponse>;
    /**
     * 
     * @type {string}
     * @memberof DocumentLookupResponse
     */
    'nextToken'?: string;
    /**
     * The total number of results found
     * @type {number}
     * @memberof DocumentLookupResponse
     */
    'total'?: number;
}

