/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentType } from './document-type';

/**
 * 
 * @export
 * @interface DocumentRemoteUploadRequestDocumentsInner
 */
export interface DocumentRemoteUploadRequestDocumentsInner {
    /**
     * 
     * @type {number}
     * @memberof DocumentRemoteUploadRequestDocumentsInner
     */
    'bucketId': number;
    /**
     * Data that is passed through on callback
     * @type {string}
     * @memberof DocumentRemoteUploadRequestDocumentsInner
     */
    'callbackData'?: string;
    /**
     * URL where GroundX will post status changes to the ingest request
     * @type {string}
     * @memberof DocumentRemoteUploadRequestDocumentsInner
     */
    'callbackUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRemoteUploadRequestDocumentsInner
     */
    'fileName'?: string;
    /**
     * 
     * @type {DocumentType}
     * @memberof DocumentRemoteUploadRequestDocumentsInner
     */
    'fileType'?: DocumentType;
    /**
     * 
     * @type {object}
     * @memberof DocumentRemoteUploadRequestDocumentsInner
     */
    'metadata'?: object;
    /**
     * Source document URL
     * @type {string}
     * @memberof DocumentRemoteUploadRequestDocumentsInner
     */
    'sourceUrl': string;
}

