/*
EyeLevel\'s GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The type of document (one of the seven currently supported file types)
 * @export
 * @enum {string}
 */
export type DocumentType = 'txt' | 'docx' | 'pptx' | 'xlsx' | 'pdf' | 'png' | 'jpg' | 'csv' | 'tsv' | 'json'

