/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DocumentRemoteUploadRequestDocumentsInner } from './document-remote-upload-request-documents-inner';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentType } from './document-type';

/**
 * 
 * @export
 * @interface DocumentRemoteUploadRequest
 */
export interface DocumentRemoteUploadRequest {
    /**
     * 
     * @type {number}
     * @memberof DocumentRemoteUploadRequest
     */
    'bucketId': number;
    /**
     * 
     * @type {string}
     * @memberof DocumentRemoteUploadRequest
     */
    'sourceUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRemoteUploadRequest
     */
    'callbackData'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRemoteUploadRequest
     */
    'callbackUrl'?: string;
    /**
     * 
     * @type {object}
     * @memberof DocumentRemoteUploadRequest
     */
    'metadata'?: object;
    /**
     * 
     * @type {DocumentType}
     * @memberof DocumentRemoteUploadRequest
     */
    'type'?: DocumentType;
    /**
     * 
     * @type {Array<DocumentRemoteUploadRequestDocumentsInner>}
     * @memberof DocumentRemoteUploadRequest
     */
    'documents'?: Array<DocumentRemoteUploadRequestDocumentsInner>;
}

