/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DocumentLocalUploadRequestMetadata } from './document-local-upload-request-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentType } from './document-type';

/**
 * 
 * @export
 * @interface DocumentLocalUploadRequest
 */
export interface DocumentLocalUploadRequest {
    /**
     * 
     * @type {Array<Uint8Array | File>}
     * @memberof DocumentLocalUploadRequest
     */
    'blob': Array<Uint8Array | File>;
    /**
     * 
     * @type {DocumentLocalUploadRequestMetadata}
     * @memberof DocumentLocalUploadRequest
     */
    'metadata': DocumentLocalUploadRequestMetadata;
}

