/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentType } from './document-type';

/**
 * 
 * @export
 * @interface DocumentRemoteIngestRequestDocumentsInner
 */
export interface DocumentRemoteIngestRequestDocumentsInner {
    /**
     * the bucketId of the bucket which this remote file will be ingested to.
     * @type {number}
     * @memberof DocumentRemoteIngestRequestDocumentsInner
     */
    'bucketId': number;
    /**
     * The name of the file being ingested
     * @type {string}
     * @memberof DocumentRemoteIngestRequestDocumentsInner
     */
    'fileName'?: string;
    /**
     * The type of document (one of the seven currently supported file types)
     * @type {DocumentType}
     * @memberof DocumentRemoteIngestRequestDocumentsInner
     */
    'fileType'?: DocumentType;
    /**
     * Custom metadata which can be used to influence GroundX\'s search functionality. This data can be used to further hone GroundX search.
     * @type {object}
     * @memberof DocumentRemoteIngestRequestDocumentsInner
     */
    'searchData'?: object;
    /**
     * The URL of the document being ingested by GroundX.
     * @type {string}
     * @memberof DocumentRemoteIngestRequestDocumentsInner
     */
    'sourceUrl': string;
}

