/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentLocalIngestRequestInnerMetadata } from './document-local-ingest-request-inner-metadata';

/**
 * 
 * @export
 * @interface DocumentLocalIngestRequestInner
 */
export interface DocumentLocalIngestRequestInner {
    /**
     * The actual file being ingested.
     * @type {Uint8Array | File | buffer.File}
     * @memberof DocumentLocalIngestRequestInner
     */
    'blob': Uint8Array | File | buffer.File;
    /**
     * 
     * @type {DocumentLocalIngestRequestInnerMetadata}
     * @memberof DocumentLocalIngestRequestInner
     */
    'metadata': DocumentLocalIngestRequestInnerMetadata;
}

