/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentLocalUploadRequestInnerMetadata } from './document-local-upload-request-inner-metadata';

/**
 * 
 * @export
 * @interface DocumentLocalUploadRequestInner
 */
export interface DocumentLocalUploadRequestInner {
    /**
     * The actual file being uploaded.
     * @type {Uint8Array | File | buffer.File}
     * @memberof DocumentLocalUploadRequestInner
     */
    'blob': Uint8Array | File | buffer.File;
    /**
     * 
     * @type {DocumentLocalUploadRequestInnerMetadata}
     * @memberof DocumentLocalUploadRequestInner
     */
    'metadata': DocumentLocalUploadRequestInnerMetadata;
}

