/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BucketDetail } from './bucket-detail';

/**
 * 
 * @export
 * @interface GroupDetail
 */
export interface GroupDetail {
    /**
     * The content buckets associated with the group
     * @type {Array<BucketDetail>}
     * @memberof GroupDetail
     */
    'buckets'?: Array<BucketDetail>;
    /**
     * The data time when the group was created, in RFC3339 format
     * @type {string}
     * @memberof GroupDetail
     */
    'created'?: string;
    /**
     * The number of files contained in the content buckets associated with the group
     * @type {number}
     * @memberof GroupDetail
     */
    'fileCount'?: number;
    /**
     * The total file size of files contained in the content buckets associated with the group
     * @type {string}
     * @memberof GroupDetail
     */
    'fileSize'?: string;
    /**
     * 
     * @type {number}
     * @memberof GroupDetail
     */
    'groupId': number;
    /**
     * 
     * @type {string}
     * @memberof GroupDetail
     */
    'name'?: string;
    /**
     * The data time when the group was last updated, in RFC3339 format
     * @type {string}
     * @memberof GroupDetail
     */
    'updated'?: string;
}

