/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface HealthService
 */
export interface HealthService {
    /**
     * The data time when the service status was last updated, in RFC3339 format
     * @type {string}
     * @memberof HealthService
     */
    'lastUpdate': string;
    /**
     * The name of the service
     * @type {string}
     * @memberof HealthService
     */
    'service': string;
    /**
     * The health status of the service
     * @type {string}
     * @memberof HealthService
     */
    'status': HealthServiceStatusEnum;
}

type HealthServiceStatusEnum = 'healthy' | 'degraded' | 'down' | 'unknown'


