/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProcessingStatus } from './processing-status';

/**
 * 
 * @export
 * @interface IngestResponseIngest
 */
export interface IngestResponseIngest {
    /**
     * 
     * @type {string}
     * @memberof IngestResponseIngest
     */
    'processId': string;
    /**
     * 
     * @type {ProcessingStatus}
     * @memberof IngestResponseIngest
     */
    'status': ProcessingStatus;
}

