/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ProcessingStatus } from './processing-status';

/**
 * 
 * @export
 * @interface IngestResponseIngest
 */
export interface IngestResponseIngest {
    /**
     * 
     * @type {string}
     * @memberof IngestResponseIngest
     */
    'processId': string;
    /**
     * 
     * @type {ProcessingStatus}
     * @memberof IngestResponseIngest
     */
    'status': ProcessingStatus;
}

