/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Current usage and limits for the user for the given metric
 * @export
 * @interface MeterDetail
 */
export interface MeterDetail {
    /**
     * Maximum limit for the current billing period
     * @type {number}
     * @memberof MeterDetail
     */
    'max'?: number;
    /**
     * Unique system generated ID for the meteric
     * @type {string}
     * @memberof MeterDetail
     */
    'meterId'?: string;
    /**
     * Current usage for the current billing period
     * @type {number}
     * @memberof MeterDetail
     */
    'value'?: number;
}

