/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface PreprocessorSetupRequest
 */
export interface PreprocessorSetupRequest {
    /**
     * A human readable description for your pre-processor
     * @type {string}
     * @memberof PreprocessorSetupRequest
     */
    'description'?: string;
    /**
     * A human readable name for your pre-processor
     * @type {string}
     * @memberof PreprocessorSetupRequest
     */
    'name'?: string;
    /**
     * An array of GroundedScript commands
     * @type {Array<string>}
     * @memberof PreprocessorSetupRequest
     */
    'script'?: Array<string>;
}

