/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface PreprocessorResponsePreprocessPreprocessorsInner
 */
export interface PreprocessorResponsePreprocessPreprocessorsInner {
    /**
     * preprocessor ID
     * @type {string}
     * @memberof PreprocessorResponsePreprocessPreprocessorsInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PreprocessorResponsePreprocessPreprocessorsInner
     */
    'status'?: PreprocessorResponsePreprocessPreprocessorsInnerStatusEnum;
    /**
     * human readable status description
     * @type {string}
     * @memberof PreprocessorResponsePreprocessPreprocessorsInner
     */
    'status_message'?: string;
    /**
     * 
     * @type {string}
     * @memberof PreprocessorResponsePreprocessPreprocessorsInner
     */
    'type'?: PreprocessorResponsePreprocessPreprocessorsInnerTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof PreprocessorResponsePreprocessPreprocessorsInner
     */
    'script'?: Array<string>;
}

type PreprocessorResponsePreprocessPreprocessorsInnerStatusEnum = 'ok' | 'error' | 'warning'
type PreprocessorResponsePreprocessPreprocessorsInnerTypeEnum = 'custom' | 'standard'


