/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PreprocessorSetupResponsePreprocess } from './preprocessor-setup-response-preprocess';
// May contain unused imports in some cases
// @ts-ignore
import { PreprocessorSetupResponsePreprocessPreprocessorsInner } from './preprocessor-setup-response-preprocess-preprocessors-inner';

/**
 * 
 * @export
 * @interface PreprocessorSetupResponse
 */
export interface PreprocessorSetupResponse {
    /**
     * 
     * @type {PreprocessorSetupResponsePreprocess}
     * @memberof PreprocessorSetupResponse
     */
    'preprocess'?: PreprocessorSetupResponsePreprocess;
}

