/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentDetail } from './document-detail';

/**
 * 
 * @export
 * @interface ProcessStatusResponseIngestProgressCancelled
 */
export interface ProcessStatusResponseIngestProgressCancelled {
    /**
     * 
     * @type {Array<DocumentDetail>}
     * @memberof ProcessStatusResponseIngestProgressCancelled
     */
    'documents'?: Array<DocumentDetail>;
    /**
     * 
     * @type {number}
     * @memberof ProcessStatusResponseIngestProgressCancelled
     */
    'total'?: number;
}

