/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentDetail } from './document-detail';

/**
 * 
 * @export
 * @interface ProcessStatusResponseIngestProgressCancelled
 */
export interface ProcessStatusResponseIngestProgressCancelled {
    /**
     * 
     * @type {Array<DocumentDetail>}
     * @memberof ProcessStatusResponseIngestProgressCancelled
     */
    'documents'?: Array<DocumentDetail>;
    /**
     * 
     * @type {number}
     * @memberof ProcessStatusResponseIngestProgressCancelled
     */
    'total'?: number;
}

