/*
EyeLevel\'s GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProcessStatusResponseIngestProgressCancelled } from './process-status-response-ingest-progress-cancelled';

/**
 * 
 * @export
 * @interface ProcessStatusResponseIngestProgress
 */
export interface ProcessStatusResponseIngestProgress {
    /**
     * 
     * @type {ProcessStatusResponseIngestProgressCancelled}
     * @memberof ProcessStatusResponseIngestProgress
     */
    'cancelled'?: ProcessStatusResponseIngestProgressCancelled;
    /**
     * 
     * @type {ProcessStatusResponseIngestProgressCancelled}
     * @memberof ProcessStatusResponseIngestProgress
     */
    'complete'?: ProcessStatusResponseIngestProgressCancelled;
    /**
     * 
     * @type {ProcessStatusResponseIngestProgressCancelled}
     * @memberof ProcessStatusResponseIngestProgress
     */
    'errors'?: ProcessStatusResponseIngestProgressCancelled;
    /**
     * 
     * @type {ProcessStatusResponseIngestProgressCancelled}
     * @memberof ProcessStatusResponseIngestProgress
     */
    'processing'?: ProcessStatusResponseIngestProgressCancelled;
}

