/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectCreateRequest
 */
export interface ProjectCreateRequest {
    /**
     * The name of the project being created.
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    'name': string;
    /**
     * Specify bucketName to automatically create a bucket, by the name specified, and add it to the created project.
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    'bucketName'?: string;
}

