/*
GroundX APIs

RAG Made Simple, Secure and Hallucination Free

The version of the OpenAPI document: 1.3.26
Contact: support@eyelevel.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BucketDetail } from './bucket-detail';

/**
 * 
 * @export
 * @interface ProjectDetail
 */
export interface ProjectDetail {
    /**
     * The content buckets associated with the project
     * @type {Array<BucketDetail>}
     * @memberof ProjectDetail
     */
    'buckets'?: Array<BucketDetail>;
    /**
     * The data time when the project was created, in RFC3339 format
     * @type {string}
     * @memberof ProjectDetail
     */
    'created'?: string;
    /**
     * The number of files contained in the content buckets associated with the project
     * @type {number}
     * @memberof ProjectDetail
     */
    'fileCount'?: number;
    /**
     * The total file size of files contained in the content buckets associated with the project
     * @type {string}
     * @memberof ProjectDetail
     */
    'fileSize'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetail
     */
    'projectId': number;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'name'?: string;
    /**
     * The data time when the project was last updated, in RFC3339 format
     * @type {string}
     * @memberof ProjectDetail
     */
    'updated'?: string;
}

