/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BucketDetail } from './bucket-detail';
// May contain unused imports in some cases
// @ts-ignore
import { ProjectDetail } from './project-detail';

/**
 * 
 * @export
 * @interface ProjectListResponse
 */
export interface ProjectListResponse {
    /**
     * 
     * @type {Array<ProjectDetail>}
     * @memberof ProjectListResponse
     */
    'projects'?: Array<ProjectDetail>;
}

