/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BucketDetail } from './bucket-detail';

/**
 * 
 * @export
 * @interface ProjectDetail
 */
export interface ProjectDetail {
    /**
     * 
     * @type {Array<BucketDetail>}
     * @memberof ProjectDetail
     */
    'buckets'?: Array<BucketDetail>;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'created'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetail
     */
    'fileCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'fileSize'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'projectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'updated'?: string;
}

