/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BucketDetail } from './bucket-detail';

/**
 * 
 * @export
 * @interface ProjectDetail
 */
export interface ProjectDetail {
    /**
     * 
     * @type {Array<BucketDetail>}
     * @memberof ProjectDetail
     */
    'buckets'?: Array<BucketDetail>;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'created'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetail
     */
    'fileCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'fileSize'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetail
     */
    'groupId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectDetail
     */
    'projectId': number;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetail
     */
    'updated'?: string;
}

