/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { SearchResultItem } from './search-result-item';

/**
 * 
 * @export
 * @interface SearchResponseSearch
 */
export interface SearchResponseSearch {
    /**
     * Total results
     * @type {number}
     * @memberof SearchResponseSearch
     */
    'count'?: number;
    /**
     * 
     * @type {Array<SearchResultItem>}
     * @memberof SearchResponseSearch
     */
    'results'?: Array<SearchResultItem>;
    /**
     * The search query
     * @type {string}
     * @memberof SearchResponseSearch
     */
    'query'?: string;
    /**
     * Top result relevance score
     * @type {number}
     * @memberof SearchResponseSearch
     */
    'score'?: number;
    /**
     * Combined text from results
     * @type {string}
     * @memberof SearchResponseSearch
     */
    'text'?: string;
    /**
     * For paginated results
     * @type {string}
     * @memberof SearchResponseSearch
     */
    'nextToken'?: string;
}

