/* tslint:disable */
/* eslint-disable */
/**
 * GroundX API
 * Ground Your RAG Apps in Fact not Fiction
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@groundx.ai
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SearchResponseSearch } from './search-response-search';
// May contain unused imports in some cases
// @ts-ignore
import { SearchResultItem } from './search-result-item';

/**
 * 
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * 
     * @type {SearchResponseSearch}
     * @memberof SearchResponse
     */
    'search': SearchResponseSearch;
}

