/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SearchRequestSearch
 */
export interface SearchRequestSearch {
    /**
     * The search query to be used to find relevant documentation. <WIP>
     * @type {string}
     * @memberof SearchRequestSearch
     */
    'query': string;
    /**
     * A token for pagination. If the number of documents for a given query is larger than n, the response will include a \"nextToken\" value. That token can be included in this field to retrieve the next batch of n documents.
     * @type {string}
     * @memberof SearchRequestSearch
     */
    'nextToken'?: string;
}

