/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebsiteCrawlRequestWebsitesInner } from './website-crawl-request-websites-inner';

/**
 * 
 * @export
 * @interface WebsiteCrawlRequest
 */
export interface WebsiteCrawlRequest {
    /**
     * 
     * @type {Array<WebsiteCrawlRequestWebsitesInner>}
     * @memberof WebsiteCrawlRequest
     */
    'websites': Array<WebsiteCrawlRequestWebsitesInner>;
}

