/*
GroundX API

Ground Your RAG Apps in Fact not Fiction

The version of the OpenAPI document: 1.0.0
Contact: support@groundx.ai

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebsiteCrawlRequestWebsitesInner
 */
export interface WebsiteCrawlRequestWebsitesInner {
    /**
     * 
     * @type {number}
     * @memberof WebsiteCrawlRequestWebsitesInner
     */
    'bucketId': number;
    /**
     * The maximum number of pages to crawl
     * @type {number}
     * @memberof WebsiteCrawlRequestWebsitesInner
     */
    'cap'?: number;
    /**
     * The maximum depth of linked pages to follow from the sourceUrl
     * @type {number}
     * @memberof WebsiteCrawlRequestWebsitesInner
     */
    'depth'?: number;
    /**
     * 
     * @type {object}
     * @memberof WebsiteCrawlRequestWebsitesInner
     */
    'searchData'?: object;
    /**
     * Source website URL
     * @type {string}
     * @memberof WebsiteCrawlRequestWebsitesInner
     */
    'sourceUrl': string;
}

