# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from groundx.type.document_local_upload_request_blob import DocumentLocalUploadRequestBlob
from groundx.type.document_type import DocumentType

class RequiredDocumentLocalUploadRequest(TypedDict):
    pass

class OptionalDocumentLocalUploadRequest(TypedDict, total=False):
    blob: DocumentLocalUploadRequestBlob

    bucketId: int

    fileName: str

    fileType: DocumentType

    metadata: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    callbackData: str

    callbackUrl: str

class DocumentLocalUploadRequest(RequiredDocumentLocalUploadRequest, OptionalDocumentLocalUploadRequest):
    pass
