# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from groundx.type.preprocessor_setup_request_script import PreprocessorSetupRequestScript

class RequiredPreprocessorSetupRequest(TypedDict):
    pass

class OptionalPreprocessorSetupRequest(TypedDict, total=False):
    # A human readable description for your pre-processor
    description: str

    # A human readable name for your pre-processor
    name: str

    script: PreprocessorSetupRequestScript

class PreprocessorSetupRequest(RequiredPreprocessorSetupRequest, OptionalPreprocessorSetupRequest):
    pass
