# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal

from groundx.type.preprocessor_setup_response_preprocess import PreprocessorSetupResponsePreprocess
from groundx.type.preprocessor_setup_response_preprocess_preprocessors import PreprocessorSetupResponsePreprocessPreprocessors

class RequiredPreprocessorSetupResponse(TypedDict):
    pass

class OptionalPreprocessorSetupResponse(TypedDict, total=False):
    preprocess: PreprocessorSetupResponsePreprocess

class PreprocessorSetupResponse(RequiredPreprocessorSetupResponse, OptionalPreprocessorSetupResponse):
    pass
