# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

from groundx.paths.v1_apikey.get import List


class APIKeyManagementApi(
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
