# coding: utf-8
"""
    GroundX APIs

    RAG Made Simple, Secure and Hallucination Free

    The version of the OpenAPI document: 1.3.26
    Contact: support@eyelevel.ai
    Created by: https://www.eyelevel.ai/
"""

from groundx.paths.v1_bucket.post import Create
from groundx.paths.v1_bucket_bucket_id.delete import Delete
from groundx.paths.v1_bucket_bucket_id.get import Get
from groundx.paths.v1_bucket.get import List
from groundx.paths.v1_bucket_bucket_id.put import Update


class BucketsApiGenerated(
    Create,
    Delete,
    Get,
    List,
    Update,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
