# coding: utf-8
"""
    GroundX APIs

    RAG Made Simple, Secure and Hallucination Free

    The version of the OpenAPI document: 1.3.26
    Contact: support@eyelevel.ai
    Created by: https://www.eyelevel.ai/
"""

from groundx.paths.v1_customer.get import Get


class CustomerApiGenerated(
    Get,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
