# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Created by: https://www.groundx.ai/
"""

from groundx.paths.v1_ingest_document_document_id.delete import Delete
from groundx.paths.v1_ingest_document_document_id.get import Get
from groundx.paths.v1_ingest_process_id.get import GetProcessingStatusById
from groundx.paths.v1_ingest_documents.get import List
from groundx.paths.v1_ingest_documents_id.get import Lookup
from groundx.paths.v1_ingest_documents_local.post import UploadLocal
from groundx.paths.v1_ingest_documents_remote.post import UploadRemote


class DocumentsApi(
    Delete,
    Get,
    GetProcessingStatusById,
    List,
    Lookup,
    UploadLocal,
    UploadRemote,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
