# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Created by: https://www.groundx.ai/
"""

from groundx.paths.v1_project_project_id_bucket_bucket_id.post import AddBucket
from groundx.paths.v1_project.post import Create
from groundx.paths.v1_project_project_id.delete import Delete
from groundx.paths.v1_project_project_id.get import Get
from groundx.paths.v1_project.get import List
from groundx.paths.v1_project_project_id_bucket_bucket_id.delete import RemoveBucket
from groundx.paths.v1_project_project_id.put import Update


class ProjectsApi(
    AddBucket,
    Create,
    Delete,
    Get,
    List,
    RemoveBucket,
    Update,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
