# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

import unittest

import groundx
from groundx.model.preprocessor_delete_request import PreprocessorDeleteRequest
from groundx import configuration


class TestPreprocessorDeleteRequest(unittest.TestCase):
    """PreprocessorDeleteRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
