# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

import unittest

import groundx
from groundx.model.search_response_search import SearchResponseSearch
from groundx import configuration


class TestSearchResponseSearch(unittest.TestCase):
    """SearchResponseSearch unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
