# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

import unittest

import groundx
from groundx.model.project_list_response import ProjectListResponse
from groundx import configuration


class TestProjectListResponse(unittest.TestCase):
    """ProjectListResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
