# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

import unittest

import groundx
from groundx.model.project_bind_bucket400_response import ProjectBindBucket400Response
from groundx import configuration


class TestProjectBindBucket400Response(unittest.TestCase):
    """ProjectBindBucket400Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
