# coding: utf-8

"""
    GroundX API

    Ground Your RAG Apps in Fact not Fiction

    The version of the OpenAPI document: 1.0.0
    Contact: support@groundx.ai
    Generated by: https://konfigthis.com
"""

import unittest

import groundx
from groundx.model.project_update_request_project import ProjectUpdateRequestProject
from groundx import configuration


class TestProjectUpdateRequestProject(unittest.TestCase):
    """ProjectUpdateRequestProject unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
